version: '3.5'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    networks:
      - main-network
  redis:
    image: redis:6.0.8-alpine
    networks:
      - main-network
#    environment:

  app:
    build: ./
    ports:
      - 8080:8080
      - 7001:7001
    depends_on:
      - db
      - redis
    networks:
      - main-network
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather_db
      - CACHE_HOST=redis
  migration:
    build:
      context: .
      dockerfile: DockerFileMigration
#    volumes:
#      - /db/migration:/flyway/sql
    networks:
      - main-network
    environment:
      - HOST=db
      - PORT=5432
      - USER=user
      - PASSWORD=password
      - DB=weather_db
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  weather-data:
networks:
  main-network:
    driver: bridge