openweather:
  apiKey: 4b90b3ba5659e1d08a9ecf0b7cb58188
  timeoutMs: 1000
  repeatTime: 3
  temperatureDiff: 10
server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5434}/${RDS_DB:postgres}
  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: true
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    template-resolver-order: 0

