# API
openweather:
  apiKey: 4b90b3ba5659e1d08a9ecf0b7cb58188
  timeoutMs: 1000
  repeatTime: 3
  temperatureDiff: 9
# Server
server:
  port: 8080
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: changeit
# DB
spring:
  datasource:
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5436}/${POSTGRES_DB:weather_db}
# Logging
logging:
  level:
    root: INFO
    ru:
      suvorov:
        weather: INFO
  file:
    name: logFile
    path: /logs
# Monitoring
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'



