openweather:
  apiKey: 4b90b3ba5659e1d08a9ecf0b7cb58188
  timeoutMs: 1000
  repeatTime: 3
  temperatureDiff: 9
server:
  port: 8080
spring:
  datasource:
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5436}/${POSTGRES_DB:weather_db}
#  cache
#    type: redis
#    cache-names: weather
#    redis:
#      time-to-live: 60000
#  redis:
#    host: ${CACHE_HOST:localhost}
#    port: 6379
logging:
  level:
    root: WARN
    ru:
      suvorov:
        weather: INFO
  file:
    name: logFile
    path: /logs

