openweather:
  apiKey: 4b90b3ba5659e1d08a9ecf0b7cb58188
  timeoutMs: 1000
  repeatTime: 3
  temperatureDiff: 9
server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5434}/${RDS_DB:postgres}
  cache:
    type: redis
    cache-names: weather
    redis:
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
